language: node_js
node_js:
  - 12
services:
  - docker
before_install:
  - docker build -t konstantin-shilov/node-dth .
  - docker run -p 8000:4000 -d --name nodedth konstantin-shilov/node-dth:latest
script:
  - docker exec -it nodedth sh -c "npm run lint"
deploy:
  provider: heroku
  api_key:
    secure:
  app: node-16
  on:
    repo: Konstantin-Shilov/konstantin-shilov-nodejs-otus
  skip_cleanup: 'true'
